// Generated by gencpp from file vector_map_msgs/CrossWalk.msg
// DO NOT EDIT!


#ifndef VECTOR_MAP_MSGS_MESSAGE_CROSSWALK_H
#define VECTOR_MAP_MSGS_MESSAGE_CROSSWALK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vector_map_msgs
{
template <class ContainerAllocator>
struct CrossWalk_
{
  typedef CrossWalk_<ContainerAllocator> Type;

  CrossWalk_()
    : id(0)
    , aid(0)
    , type(0)
    , bdid(0)
    , linkid(0)  {
    }
  CrossWalk_(const ContainerAllocator& _alloc)
    : id(0)
    , aid(0)
    , type(0)
    , bdid(0)
    , linkid(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _aid_type;
  _aid_type aid;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _bdid_type;
  _bdid_type bdid;

   typedef int32_t _linkid_type;
  _linkid_type linkid;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CLOSURE_LINE)
  #undef CLOSURE_LINE
#endif
#if defined(_WIN32) && defined(STRIPE_PATTERN)
  #undef STRIPE_PATTERN
#endif
#if defined(_WIN32) && defined(BICYCLE_LANE)
  #undef BICYCLE_LANE
#endif

  enum {
    CLOSURE_LINE = 0u,
    STRIPE_PATTERN = 1u,
    BICYCLE_LANE = 2u,
  };


  typedef boost::shared_ptr< ::vector_map_msgs::CrossWalk_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vector_map_msgs::CrossWalk_<ContainerAllocator> const> ConstPtr;

}; // struct CrossWalk_

typedef ::vector_map_msgs::CrossWalk_<std::allocator<void> > CrossWalk;

typedef boost::shared_ptr< ::vector_map_msgs::CrossWalk > CrossWalkPtr;
typedef boost::shared_ptr< ::vector_map_msgs::CrossWalk const> CrossWalkConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vector_map_msgs::CrossWalk_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vector_map_msgs::CrossWalk_<ContainerAllocator1> & lhs, const ::vector_map_msgs::CrossWalk_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.aid == rhs.aid &&
    lhs.type == rhs.type &&
    lhs.bdid == rhs.bdid &&
    lhs.linkid == rhs.linkid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vector_map_msgs::CrossWalk_<ContainerAllocator1> & lhs, const ::vector_map_msgs::CrossWalk_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vector_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vector_map_msgs::CrossWalk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_map_msgs::CrossWalk_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_map_msgs::CrossWalk_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "626e8d6afb39af06dfd0654aa131f1cb";
  }

  static const char* value(const ::vector_map_msgs::CrossWalk_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x626e8d6afb39af06ULL;
  static const uint64_t static_value2 = 0xdfd0654aa131f1cbULL;
};

template<class ContainerAllocator>
struct DataType< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vector_map_msgs/CrossWalk";
  }

  static const char* value(const ::vector_map_msgs::CrossWalk_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# type\n"
"uint8 CLOSURE_LINE=0\n"
"uint8 STRIPE_PATTERN=1\n"
"uint8 BICYCLE_LANE=2\n"
"\n"
"# Ver 1.00\n"
"int32 id\n"
"int32 aid\n"
"int32 type\n"
"int32 bdid\n"
"int32 linkid\n"
;
  }

  static const char* value(const ::vector_map_msgs::CrossWalk_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.aid);
      stream.next(m.type);
      stream.next(m.bdid);
      stream.next(m.linkid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CrossWalk_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vector_map_msgs::CrossWalk_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vector_map_msgs::CrossWalk_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "aid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aid);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "bdid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bdid);
    s << indent << "linkid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.linkid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VECTOR_MAP_MSGS_MESSAGE_CROSSWALK_H
