// Generated by gencpp from file vector_map_msgs/Pole.msg
// DO NOT EDIT!


#ifndef VECTOR_MAP_MSGS_MESSAGE_POLE_H
#define VECTOR_MAP_MSGS_MESSAGE_POLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vector_map_msgs
{
template <class ContainerAllocator>
struct Pole_
{
  typedef Pole_<ContainerAllocator> Type;

  Pole_()
    : plid(0)
    , vid(0)
    , length(0.0)
    , dim(0.0)  {
    }
  Pole_(const ContainerAllocator& _alloc)
    : plid(0)
    , vid(0)
    , length(0.0)
    , dim(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _plid_type;
  _plid_type plid;

   typedef int32_t _vid_type;
  _vid_type vid;

   typedef double _length_type;
  _length_type length;

   typedef double _dim_type;
  _dim_type dim;





  typedef boost::shared_ptr< ::vector_map_msgs::Pole_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vector_map_msgs::Pole_<ContainerAllocator> const> ConstPtr;

}; // struct Pole_

typedef ::vector_map_msgs::Pole_<std::allocator<void> > Pole;

typedef boost::shared_ptr< ::vector_map_msgs::Pole > PolePtr;
typedef boost::shared_ptr< ::vector_map_msgs::Pole const> PoleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vector_map_msgs::Pole_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vector_map_msgs::Pole_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vector_map_msgs::Pole_<ContainerAllocator1> & lhs, const ::vector_map_msgs::Pole_<ContainerAllocator2> & rhs)
{
  return lhs.plid == rhs.plid &&
    lhs.vid == rhs.vid &&
    lhs.length == rhs.length &&
    lhs.dim == rhs.dim;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vector_map_msgs::Pole_<ContainerAllocator1> & lhs, const ::vector_map_msgs::Pole_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vector_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vector_map_msgs::Pole_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vector_map_msgs::Pole_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_map_msgs::Pole_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vector_map_msgs::Pole_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_map_msgs::Pole_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vector_map_msgs::Pole_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vector_map_msgs::Pole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d65404b5e1f838856c9aeaa9d94be8";
  }

  static const char* value(const ::vector_map_msgs::Pole_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d65404b5e1f838ULL;
  static const uint64_t static_value2 = 0x856c9aeaa9d94be8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vector_map_msgs::Pole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vector_map_msgs/Pole";
  }

  static const char* value(const ::vector_map_msgs::Pole_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vector_map_msgs::Pole_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ver 1.00\n"
"int32 plid\n"
"int32 vid\n"
"float64 length\n"
"float64 dim\n"
;
  }

  static const char* value(const ::vector_map_msgs::Pole_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vector_map_msgs::Pole_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plid);
      stream.next(m.vid);
      stream.next(m.length);
      stream.next(m.dim);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pole_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vector_map_msgs::Pole_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vector_map_msgs::Pole_<ContainerAllocator>& v)
  {
    s << indent << "plid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.plid);
    s << indent << "vid: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vid);
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "dim: ";
    Printer<double>::stream(s, indent + "  ", v.dim);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VECTOR_MAP_MSGS_MESSAGE_POLE_H
