// Generated by gencpp from file hellocm_msgs/CM2Ext_Test.msg
// DO NOT EDIT!


#ifndef HELLOCM_MSGS_MESSAGE_CM2EXT_TEST_H
#define HELLOCM_MSGS_MESSAGE_CM2EXT_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hellocm_msgs
{
template <class ContainerAllocator>
struct CM2Ext_Test_
{
  typedef CM2Ext_Test_<ContainerAllocator> Type;

  CM2Ext_Test_()
    : header()
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , test1(0.0)  {
    }
  CM2Ext_Test_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time()
    , cycleno(0)
    , synthdelay(0.0)
    , test1(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _time_type;
  _time_type time;

   typedef int64_t _cycleno_type;
  _cycleno_type cycleno;

   typedef double _synthdelay_type;
  _synthdelay_type synthdelay;

   typedef double _test1_type;
  _test1_type test1;





  typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> const> ConstPtr;

}; // struct CM2Ext_Test_

typedef ::hellocm_msgs::CM2Ext_Test_<std::allocator<void> > CM2Ext_Test;

typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_Test > CM2Ext_TestPtr;
typedef boost::shared_ptr< ::hellocm_msgs::CM2Ext_Test const> CM2Ext_TestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator1> & lhs, const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.cycleno == rhs.cycleno &&
    lhs.synthdelay == rhs.synthdelay &&
    lhs.test1 == rhs.test1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator1> & lhs, const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hellocm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e98f5e5adb0afef7c137fcc7a674d4ca";
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe98f5e5adb0afef7ULL;
  static const uint64_t static_value2 = 0xc137fcc7a674d4caULL;
};

template<class ContainerAllocator>
struct DataType< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hellocm_msgs/CM2Ext_Test";
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Message from CarMaker ROS Node to external ROS Node\n"
"#\n"
"\n"
"# General\n"
"Header  header                                 # General ROS Header (optional)\n"
"time    time                                   # ROS time when message was sent (optional)\n"
"int64   cycleno                                # Cycle number since simulation start (optional)\n"
"float64 synthdelay                             # Synthetic delay to check synchronization (optional)\n"
"\n"
"float64 test1	# by kimna\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.cycleno);
      stream.next(m.synthdelay);
      stream.next(m.test1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CM2Ext_Test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hellocm_msgs::CM2Ext_Test_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "cycleno: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cycleno);
    s << indent << "synthdelay: ";
    Printer<double>::stream(s, indent + "  ", v.synthdelay);
    s << indent << "test1: ";
    Printer<double>::stream(s, indent + "  ", v.test1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLOCM_MSGS_MESSAGE_CM2EXT_TEST_H
