// Generated by gencpp from file hellocm_msgs/Ext2CM_Test.msg
// DO NOT EDIT!


#ifndef HELLOCM_MSGS_MESSAGE_EXT2CM_TEST_H
#define HELLOCM_MSGS_MESSAGE_EXT2CM_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hellocm_msgs
{
template <class ContainerAllocator>
struct Ext2CM_Test_
{
  typedef Ext2CM_Test_<ContainerAllocator> Type;

  Ext2CM_Test_()
    : header()
    , time()
    , cycleno(0)  {
    }
  Ext2CM_Test_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time()
    , cycleno(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _time_type;
  _time_type time;

   typedef int64_t _cycleno_type;
  _cycleno_type cycleno;





  typedef boost::shared_ptr< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> const> ConstPtr;

}; // struct Ext2CM_Test_

typedef ::hellocm_msgs::Ext2CM_Test_<std::allocator<void> > Ext2CM_Test;

typedef boost::shared_ptr< ::hellocm_msgs::Ext2CM_Test > Ext2CM_TestPtr;
typedef boost::shared_ptr< ::hellocm_msgs::Ext2CM_Test const> Ext2CM_TestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator1> & lhs, const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.cycleno == rhs.cycleno;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator1> & lhs, const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hellocm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29a07ad10a375b2d8f0acd60cd83c7a9";
  }

  static const char* value(const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29a07ad10a375b2dULL;
  static const uint64_t static_value2 = 0x8f0acd60cd83c7a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hellocm_msgs/Ext2CM_Test";
  }

  static const char* value(const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Message from external ROS Node to CarMaker ROS Node\n"
"#\n"
"\n"
"# General\n"
"Header  header                                 # General ROS Header (optional)\n"
"time    time                                   # ROS time when message was sent (optional)\n"
"int64   cycleno                                # Cycle number since simulation start (optional)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.cycleno);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ext2CM_Test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hellocm_msgs::Ext2CM_Test_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "cycleno: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cycleno);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLOCM_MSGS_MESSAGE_EXT2CM_TEST_H
