// Generated by gencpp from file autoware_map_msgs/LaneSignalLightRelation.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_LANESIGNALLIGHTRELATION_H
#define AUTOWARE_MAP_MSGS_MESSAGE_LANESIGNALLIGHTRELATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct LaneSignalLightRelation_
{
  typedef LaneSignalLightRelation_<ContainerAllocator> Type;

  LaneSignalLightRelation_()
    : lane_id(0)
    , signal_light_id(0)  {
    }
  LaneSignalLightRelation_(const ContainerAllocator& _alloc)
    : lane_id(0)
    , signal_light_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;

   typedef int32_t _signal_light_id_type;
  _signal_light_id_type signal_light_id;





  typedef boost::shared_ptr< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> const> ConstPtr;

}; // struct LaneSignalLightRelation_

typedef ::autoware_map_msgs::LaneSignalLightRelation_<std::allocator<void> > LaneSignalLightRelation;

typedef boost::shared_ptr< ::autoware_map_msgs::LaneSignalLightRelation > LaneSignalLightRelationPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::LaneSignalLightRelation const> LaneSignalLightRelationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator2> & rhs)
{
  return lhs.lane_id == rhs.lane_id &&
    lhs.signal_light_id == rhs.signal_light_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56f58c04c9fd01d81da77e983aaab87b";
  }

  static const char* value(const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56f58c04c9fd01d8ULL;
  static const uint64_t static_value2 = 0x1da77e983aaab87bULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/LaneSignalLightRelation";
  }

  static const char* value(const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents relation between a lane and a signal in a map.\n"
"\n"
"# Id of refering Lane object\n"
"int32 lane_id\n"
"\n"
"# Id of SignalLight object that must be recognized when vehicle is driving the refering lane. \n"
"int32 signal_light_id\n"
;
  }

  static const char* value(const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lane_id);
      stream.next(m.signal_light_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneSignalLightRelation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::LaneSignalLightRelation_<ContainerAllocator>& v)
  {
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "signal_light_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signal_light_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_LANESIGNALLIGHTRELATION_H
