// Generated by gencpp from file autoware_map_msgs/Signal.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_SIGNAL_H
#define AUTOWARE_MAP_MSGS_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct Signal_
{
  typedef Signal_<ContainerAllocator> Type;

  Signal_()
    : signal_id(0)  {
    }
  Signal_(const ContainerAllocator& _alloc)
    : signal_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _signal_id_type;
  _signal_id_type signal_id;





  typedef boost::shared_ptr< ::autoware_map_msgs::Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Signal_

typedef ::autoware_map_msgs::Signal_<std::allocator<void> > Signal;

typedef boost::shared_ptr< ::autoware_map_msgs::Signal > SignalPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::Signal const> SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_map_msgs::Signal_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::Signal_<ContainerAllocator2> & rhs)
{
  return lhs.signal_id == rhs.signal_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_map_msgs::Signal_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::Signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::Signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce22ff7abffe33a847c3be7603063bea";
  }

  static const char* value(const ::autoware_map_msgs::Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce22ff7abffe33a8ULL;
  static const uint64_t static_value2 = 0x47c3be7603063beaULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/Signal";
  }

  static const char* value(const ::autoware_map_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents traffic signal(traffic light) in a map.\n"
"\n"
"# Id of this Signal(traffic light) object. Must be unique among all signals in a map. \n"
"int32 signal_id\n"
;
  }

  static const char* value(const ::autoware_map_msgs::Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::Signal_<ContainerAllocator>& v)
  {
    s << indent << "signal_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signal_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_SIGNAL_H
