// Generated by gencpp from file autoware_map_msgs/WaypointRelationArray.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTRELATIONARRAY_H
#define AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTRELATIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <autoware_map_msgs/WaypointRelation.h>

namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct WaypointRelationArray_
{
  typedef WaypointRelationArray_<ContainerAllocator> Type;

  WaypointRelationArray_()
    : header()
    , data()  {
    }
  WaypointRelationArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::autoware_map_msgs::WaypointRelation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::autoware_map_msgs::WaypointRelation_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointRelationArray_

typedef ::autoware_map_msgs::WaypointRelationArray_<std::allocator<void> > WaypointRelationArray;

typedef boost::shared_ptr< ::autoware_map_msgs::WaypointRelationArray > WaypointRelationArrayPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::WaypointRelationArray const> WaypointRelationArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cbc28f0f2b9f8544eb0ee2045b3e562";
  }

  static const char* value(const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cbc28f0f2b9f854ULL;
  static const uint64_t static_value2 = 0x4eb0ee2045b3e562ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/WaypointRelationArray";
  }

  static const char* value(const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This consists of multiple WaypointRelation objects in a map. \n"
"\n"
"Header header\n"
"WaypointRelation[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: autoware_map_msgs/WaypointRelation\n"
"# This represents the connection between a waypoint and a lane.\n"
"\n"
"# Id of refering Waypoint object\n"
"int32 waypoint_id\n"
"\n"
"# Id of Waypoint object that follows the refering waypoint\n"
"int32 next_waypoint_id\n"
"\n"
"# Direction from the refering waypoint to next waypoint in [rad].\n"
"# The angle is calculated from North in counter clockwise. \n"
"float64 yaw\n"
"\n"
"# Blinker that vehicle must light up when driving from waypoint to next_waypoint\n"
"int32 blinker\n"
"\n"
"# Distance between waypoint and next_waypoint\n"
"float64 distance\n"
;
  }

  static const char* value(const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointRelationArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::WaypointRelationArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::autoware_map_msgs::WaypointRelation_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTRELATIONARRAY_H
