// Generated by gencpp from file autoware_map_msgs/WaypointLaneRelation.msg
// DO NOT EDIT!


#ifndef AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTLANERELATION_H
#define AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTLANERELATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autoware_map_msgs
{
template <class ContainerAllocator>
struct WaypointLaneRelation_
{
  typedef WaypointLaneRelation_<ContainerAllocator> Type;

  WaypointLaneRelation_()
    : waypoint_id(0)
    , lane_id(0)
    , order(0)  {
    }
  WaypointLaneRelation_(const ContainerAllocator& _alloc)
    : waypoint_id(0)
    , lane_id(0)
    , order(0)  {
  (void)_alloc;
    }



   typedef int32_t _waypoint_id_type;
  _waypoint_id_type waypoint_id;

   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;

   typedef int32_t _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointLaneRelation_

typedef ::autoware_map_msgs::WaypointLaneRelation_<std::allocator<void> > WaypointLaneRelation;

typedef boost::shared_ptr< ::autoware_map_msgs::WaypointLaneRelation > WaypointLaneRelationPtr;
typedef boost::shared_ptr< ::autoware_map_msgs::WaypointLaneRelation const> WaypointLaneRelationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator2> & rhs)
{
  return lhs.waypoint_id == rhs.waypoint_id &&
    lhs.lane_id == rhs.lane_id &&
    lhs.order == rhs.order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator1> & lhs, const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autoware_map_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8f61b7c5089da0aa24b1fd1cd929398";
  }

  static const char* value(const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8f61b7c5089da0aULL;
  static const uint64_t static_value2 = 0xa24b1fd1cd929398ULL;
};

template<class ContainerAllocator>
struct DataType< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autoware_map_msgs/WaypointLaneRelation";
  }

  static const char* value(const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents the connection between waypoints and lanes\n"
"\n"
"# Id of refering Waypoint object\n"
"int32 waypoint_id\n"
"\n"
"# Id of Lane object which refering waypoint belongs to \n"
"int32 lane_id\n"
"\n"
"# order of the waypoint in the lane. \n"
"# e.g. starting waypoint of the lane will have order of 0. \n"
"int32 order\n"
;
  }

  static const char* value(const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint_id);
      stream.next(m.lane_id);
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointLaneRelation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autoware_map_msgs::WaypointLaneRelation_<ContainerAllocator>& v)
  {
    s << indent << "waypoint_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint_id);
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "order: ";
    Printer<int32_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOWARE_MAP_MSGS_MESSAGE_WAYPOINTLANERELATION_H
