// Generated by gencpp from file tablet_socket_msgs/gear_cmd.msg
// DO NOT EDIT!


#ifndef TABLET_SOCKET_MSGS_MESSAGE_GEAR_CMD_H
#define TABLET_SOCKET_MSGS_MESSAGE_GEAR_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tablet_socket_msgs
{
template <class ContainerAllocator>
struct gear_cmd_
{
  typedef gear_cmd_<ContainerAllocator> Type;

  gear_cmd_()
    : header()
    , gear(0)  {
    }
  gear_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gear(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct gear_cmd_

typedef ::tablet_socket_msgs::gear_cmd_<std::allocator<void> > gear_cmd;

typedef boost::shared_ptr< ::tablet_socket_msgs::gear_cmd > gear_cmdPtr;
typedef boost::shared_ptr< ::tablet_socket_msgs::gear_cmd const> gear_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator1> & lhs, const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator1> & lhs, const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tablet_socket_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8c00e2df1bb0287311560f49a754159";
  }

  static const char* value(const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8c00e2df1bb0287ULL;
  static const uint64_t static_value2 = 0x311560f49a754159ULL;
};

template<class ContainerAllocator>
struct DataType< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tablet_socket_msgs/gear_cmd";
  }

  static const char* value(const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 gear\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gear_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tablet_socket_msgs::gear_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tablet_socket_msgs::gear_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TABLET_SOCKET_MSGS_MESSAGE_GEAR_CMD_H
